### ISSUE TITLE
Updation/creation happens even if required field is left empty.

### ISSUE THREAD

**Issue by Infinity-Intellect** [curefit/react-crux#118] opened 2020-12-17 14:32 UTC
Currently, adding `required:true` to any field in the schema definition results in a UI-level indication with a red `*`. But it does not prevent the user from creating or updating the data if the required field is left empty.

Steps to reproduce:
1. Add required for any of the fields in the schema definition during creation/updation.
2. Leave the field empty.
3. Click Create/Update.
![CruxIssue](https://user-images.githubusercontent.com/49329642/102500847-c346aa80-40a2-11eb-8896-83f5fbcddb99.PNG)

**Comment by ankitcf** [comment] 2020-12-18 06:14
@umangdarji-dev can you help fix this ?

**Comment by kunal15595** [comment] 2020-12-24 07:48
as if now, `required` parameter is just indicative on UI and validated server-side.
creation/updation API call should throw an error with proper message which in turn is shown to the user

**Comment by ankitcf** [comment] 2020-12-28 04:11
@kunal15595 whats the ideal behaviour ?

**Comment by kunal15595** [comment] 2020-12-28 07:29
Intended behaviour is that user should get the feedback on UI, with proper error message(constructively guiding the user to correct the modal details).
Better question to ask is whether form validation be within the scope of this project.

Even if we include such validations on the client side, we'll be having those duplicated on server side(as client side validations can be by-passed), moreover some validations will be specific to server-side like database constraints, if any.

**Comment by ankitcf** [comment] 2020-12-28 17:05
Yes I feel it should be in scope of the project. react-crux is a UI level library which is agnostic to server side stack and should handle missing / invalid params before sending to server. Atleast these messages should also be agnostic to server side stack. Can you try to see how much work this is ?

**Comment by kunal15595** [comment] 2021-08-09 15:16
resolved in #131

**Closed by kunal15595** 2021-08-09 15:16 UTC
